/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicio_mysql;

import javax.xml.transform.Result;
import java.sql.*;

public class App {

    public static void main(String[] args) throws SQLException, ClassNotFoundException {

        ServicioUsuario su = new ServicioUsuario();
        for (Usuario u : su.getUsuarios()){
            System.out.println(u);
        }

    }
}
